steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/redoc-cli', '.']
- name: 'gcr.io/${PROJECT_ID}/redoc-cli'
  args: ['--help']

images: ['gcr.io/${PROJECT_ID}/redoc-cli']
tags: ['k-kawa']
